### ISSUE TITLE
Error in drawCell

### ISSUE THREAD

**Issue by adzjtrna** [svalvaro/drawCell#3]
Hi, Thank you for the package - nice idea!
It does not work to me, though!
I have installed webshot2 and installation worked as it should. When I am trying to use provided examples I got an error.
Any solution?
![image](https://user-images.githubusercontent.com/45979245/162036688-95e8f054-466f-49b3-9243-82cfb484582a.png)
Thank you!
&J

**Comment by phancanhtrinh** [comment]
I have the same issue! hope some people solve it.
Thank you !

**Comment by svalvaro** [comment]
Hey @adzjtrna and @phancanhtrinh , I will heavily start working on this project again. Next week I will solve this issue. Btw, I'm sorry for the late response, I did not get notified by the issue.

**Comment by svalvaro** [comment]
Hey @adzjtrna and @phancanhtrinh I just wanted to let you know that this issue has been fixed #5, now drawCell produces higher quality vector images and you can have multiple colors, besides we're working on a Shiny App to make it even easier to use.

`drawCell(organism_identifier = '9606',sl_ids = c('SL0095','SL0154'), colour_sl = c('red','blue'))`
![image](https://user-images.githubusercontent.com/71273913/199465526-08d49a6d-29d0-417d-8ba7-67c654140d05.png)

Again, my apologies for taking a long time to fix this issue, since I had not been notified of it.

**Comment by adzjtrna** [comment]
Thank you, Alvaro!
Thanks for the package, update and for the fixing the issue!
I'll try to use drawCell soon.
Kindest regards,
Andrzej
